# workflow의 이름으로, 지정하지 않으면 경로를 이름으로 설정함
name: pr test

# main 브랜치로 push / pull request 할 때 수행되도록 설정
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# workflows는 하나 이상의 job으로 구성된다.
jobs:
  test:
    name: merge-test
    runs-on: ubuntu-latest # 어느 운영체제에서 실행할
    steps:
      - uses: actions/checkout@v3 # 제 3자가 만든 action을 사용하고 싶을 때 사용,
      - name: Set up JDK 17 # 위의 yml 파일에서 actions/checkout@v3 와 actions/setup-java@v3 를 통해 우리의 branch를 현재 비어있는 ubuntu에 내려받도록 하였고,
        uses: actions/setup-java@v3 #  java를 다운받도록 했다.
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew  # bash에서 실행할 명령어를 정의한다.
        run: chmod +x gradlew # gradlew를 실행할 권한을 부여
      - name: Test with Gradle
        run: ./gradlew build # 해당 java 코드를 빌드함
